### ISSUE TITLE
Debug `depcheck`

### ISSUE THREAD

**Issue by AuHau** [ethersphere/swarm-cid-js#3]
Currently `depcheck` can't parse Typescrip:

```
  depcheck:checkFile:error /Users/adam/Projects/swarm/swarm-cid-js/src/index.ts [AsyncFunction: parseTypescript] TypeError: p is not iterable
    at /Users/adam/Projects/swarm/swarm-cid-js/node_modules/@babel/parser/lib/index.js:10658:43
    at Array.some (<anonymous>)
    at hasPlugin (/Users/adam/Projects/swarm/swarm-cid-js/node_modules/@babel/parser/lib/index.js:10654:18)
    at validatePlugins (/Users/adam/Projects/swarm/swarm-cid-js/node_modules/@babel/parser/lib/index.js:10693:7)
    at getParser (/Users/adam/Projects/swarm/swarm-cid-js/node_modules/@babel/parser/lib/index.js:15283:5)
    at parse (/Users/adam/Projects/swarm/swarm-cid-js/node_modules/@babel/parser/lib/index.js:15254:12)
    at parseTypescript (/Users/adam/Projects/swarm/swarm-cid-js/node_modules/depcheck/dist/parser/typescript.js:17:28)
    at async getDependencies (/Users/adam/Projects/swarm/swarm-cid-js/node_modules/depcheck/dist/check.js:71:18)
    at async Promise.all (index 385)
    at async cli (/Users/adam/Projects/swarm/swarm-cid-js/node_modules/depcheck/dist/cli.js:93:28) +0ms
```

I have disabled `depcheck` for now, but we should revisit it later on.

**Comment by judofyr** [comment]
FYI: This should be fixed by https://github.com/depcheck/depcheck/pull/691.
